
os: Visual Studio 2017

environment:
    OPENSSL_DIR: "C:\\OpenSSL-v111-Win64"
    SSL_CERT_FILE: "C:\\OpenSSL-v111-Win64\\certs\\cacert.pem"

    matrix:
        - channel: stable
          target: x86_64-pc-windows-msvc
        - channel: nightly
          target: x86_64-pc-windows-msvc

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %target%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc -vV
    - cargo -vV

build: false

test_script:
    - cargo build --release
