
# Local bind address
bind_addr = "localhost:1080"

# Server 1 settings
[[server]]
password = "your_server1_pass"
server_addr = "example1.com:2000"
encrypt_method = "chacha20-ietf-poly1305"

# Server 2 settings
[[server]]
password = "your_server2_pass"
server_addr = "example2.com:2001"
encrypt_method = "aes-256-cfb"
